# Generated by Django 3.2.7 on 2022-04-24 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_number', models.IntegerField(unique=True, verbose_name='Номер аудитории')),
                ('audience_type', models.CharField(choices=[('Лекционная', 'Лекционная'), ('Лабораторная', 'Лабораторная')], default='', max_length=70, verbose_name='Тип аудитории')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=75, unique=True, verbose_name='Название корпуса')),
                ('address', models.CharField(max_length=175, verbose_name='Адрес корпуса')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='education_form',
            field=models.CharField(default='Нет', max_length=170, verbose_name='Форма обучения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='criterion',
            name='name',
            field=models.CharField(max_length=320, unique=True, verbose_name='Содержание критерия'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=320, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='STR.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(blank=True, default=None, max_length=320, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='Jesus', max_length=320, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(default='Christ', max_length=320, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=320, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=320, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lastname',
            field=models.CharField(blank=True, default=None, max_length=320, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=320, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=320, verbose_name='Фамилия'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('C 8:00 до 9:30', 'C 8:00 до 9:30'), ('С 9:45 до 11:15', 'С 9:45 до 11:15'), ('С 11:30 до 13:15', 'С 11:30 до 13:15'), ('С 13:30 до 15:00', 'С 13:30 до 15:00'), ('С 15:15 до 16:45', 'С 15:15 до 16:45'), ('С 17:00 до 18:30', 'С 17:00 до 18:30')], default='', max_length=40, verbose_name='Время')),
                ('weekday', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота')], default='', max_length=20, verbose_name='День недели')),
                ('even_week', models.CharField(choices=[('Числитель', 'Числитель'), ('Знаменатель', 'Знаменатель')], default='', max_length=20, verbose_name='Четность')),
                ('subgroup_number', models.CharField(choices=[('Подгруппа №1', 'Подгруппа №1'), ('Подгруппа №2', 'Подгруппа №2')], default='', max_length=20, verbose_name='Подгруппа')),
                ('semester_year', models.CharField(max_length=70, verbose_name='Семестр')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STR.audience', verbose_name='Аудитория')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STR.group', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STR.subject', verbose_name='Дисциплина')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STR.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.AddField(
            model_name='audience',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STR.campus', verbose_name='Корпус'),
        ),
    ]
