# Generated by Django 3.2.7 on 2022-04-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_number', models.IntegerField(unique=True, verbose_name='Номер аудитории')),
                ('audience_type', models.CharField(max_length=70, verbose_name='Тип аудитории')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=75, unique=True, verbose_name='Название корпуса')),
                ('address', models.CharField(max_length=175, verbose_name='Адресс корпуса')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='education_form',
            field=models.CharField(default='Нет', max_length=170, verbose_name='Форма обучения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='criterion',
            name='name',
            field=models.CharField(max_length=320, unique=True, verbose_name='Содержание критерия'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=320, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='STR.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(blank=True, default=None, max_length=320, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='Jesus', max_length=320, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(default='Christ', max_length=320, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=320, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=320, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lastname',
            field=models.CharField(blank=True, default=None, max_length=320, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=320, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=320, verbose_name='Фамилия'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=40, verbose_name='Время')),
                ('weekday', models.CharField(max_length=20, verbose_name='День недели')),
                ('even_week', models.CharField(max_length=20, verbose_name='Четность')),
                ('semester_year', models.CharField(max_length=70, verbose_name='Семестр')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STR.audience')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STR.group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STR.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STR.teacher')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.AddField(
            model_name='audience',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STR.campus'),
        ),
    ]
