# Generated by Django 4.0.4 on 2022-05-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0002_remove_user_date_registration_user_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='education_form',
            field=models.CharField(choices=[('Очная', 'Очная'), ('Очно-заочная', 'Очно-заочная'), ('Заочная', 'Заочная')], max_length=170, verbose_name='Форма обучения'),
        ),
    ]
