# Generated by Django 4.0.4 on 2022-05-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0002_auto_20220424_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
