# Generated by Django 3.2.7 on 2021-10-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0003_person_student_subject_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField(verbose_name='Номер вопроса')),
                ('mark', models.IntegerField(verbose_name='Оценка')),
            ],
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='markAVG',
            new_name='mark_avg',
        ),
    ]
