# Generated by Django 4.0.4 on 2022-05-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0003_alter_group_education_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='time',
            new_name='time_range',
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject_type',
            field=models.CharField(choices=[('Лекция', 'Лекция'), ('Практика', 'Практика')], default='Лекция', max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='type',
        ),
    ]
