# Generated by Django 4.0.4 on 2022-05-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0004_attendance_delete_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Посещаемость', 'verbose_name_plural': 'Посещаемость'},
        ),
        migrations.AddField(
            model_name='group',
            name='subgroup_number',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2)], default=1, verbose_name='Подгруппа'),
        ),
    ]
