# Generated by Django 4.0.4 on 2022-05-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0004_rename_time_schedule_time_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subject_type',
            field=models.CharField(choices=[('Лекция', 'Лекция'), ('Практика', 'Практика')], default='Лекция', max_length=50, verbose_name='Тип занятия'),
        ),
    ]
