# Generated by Django 4.0.4 on 2022-05-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0005_alter_schedule_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subgroup_number',
            field=models.SmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], default=None, null=True, verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subgroup_number',
            field=models.SmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], default=None, null=True, verbose_name='Подгруппа'),
        ),
    ]
