# Generated by Django 4.0.4 on 2022-05-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0005_alter_attendance_options_group_subgroup_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='subgroup_number',
        ),
        migrations.AddField(
            model_name='student',
            name='subgroup_number',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2)], default=1, verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subgroup_number',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2)], default=1, verbose_name='Подгруппа'),
        ),
    ]
