# Generated by Django 4.0.4 on 2022-05-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0006_alter_schedule_subgroup_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='even_week',
            field=models.CharField(blank=True, choices=[('Числитель', 'Числитель'), ('Знаменатель', 'Знаменатель')], default=None, max_length=20, null=True, verbose_name='Четность'),
        ),
    ]
