# Generated by Django 4.0.4 on 2022-05-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0007_alter_schedule_even_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time_range',
            field=models.CharField(choices=[(1, 'C 8:00 до 9:30'), (2, 'С 9:45 до 11:15'), (3, 'С 11:30 до 13:15'), (4, 'С 13:30 до 15:00'), (5, 'С 15:15 до 16:45'), (6, 'С 17:00 до 18:30')], default='', max_length=40, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.CharField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], default='', max_length=20, verbose_name='День недели'),
        ),
    ]
