# Generated by Django 4.0.4 on 2022-05-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0010_alter_schedule_subgroup_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='even_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Всегда'), (1, 'Числитель'), (2, 'Знаменатель')], default=0, max_length=20, verbose_name='Четность'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subgroup_number',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Нет'), (1, 'Первая'), (2, 'Вторая')], default=0, verbose_name='Подгруппа'),
        ),
    ]
