# Generated by Django 3.2.7 on 2022-05-23 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0011_alter_schedule_even_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='STR.audience', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='STR.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subgroup_number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Первая'), (2, 'Вторая')], default=0, null=True, verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='STR.subject', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_type',
            field=models.CharField(blank=True, choices=[('Лекция', 'Лекция'), ('Практика', 'Практика')], default='Лекция', max_length=50, null=True, verbose_name='Тип занятия'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='STR.teacher', verbose_name='Преподаватель'),
        ),
    ]
