# Generated by Django 3.2.7 on 2022-05-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0012_auto_20220524_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lesson_date',
            field=models.DateField(default=None, verbose_name='Дата'),
        ),
    ]
