# Generated by Django 3.2.7 on 2022-05-28 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STR', '0013_attendance_lesson_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Журнал посещаемости', 'verbose_name_plural': 'Журнал посещаемости'},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='lesson_date',
            new_name='subject_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='schedule',
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='STR.subject'),
            preserve_default=False,
        ),
    ]
